package ezra.mit.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_SIGNUP = "signup"
const val ROUTE_HOME = "home"
const val ROUTE_ABOUT = "about"
const val ROUTE_UPPER = "upperbody"
const val ROUTE_LOWER = "lowerbody"
const val ROUTE_LEGS = "legs"
const val ROUTE_CHEST = "chest"
const val ROUTE_ARMS = "arms"
const val ROUTE_ABS = "abs"
const val ROUTE_ARMSBEGINNER = "armsbeginner"
const val ROUTE_ARMSINTERMEDIATE = "armsintermediate"
const val ROUTE_ARMSADVANCED = "armsadvanced"
const val ROUTE_CHESTBEGINNER = "chestbeginner"
const val ROUTE_CHESTINTERMEDIATE = "chestintermediate"
const val ROUTE_CHESTADVANCED = "chestadvanced"
const val ROUTE_ABSBEGINNER = "absbeginner"
const val ROUTE_ABSINTERMEDIATE = "absintermediate"
const val ROUTE_ABSADVANCED = "absadvanced"
const val ROUTE_LOWERBEGINNER = "lowerbeginner"
const val ROUTE_LOWERINTERMEDIATE = "lowerintermediate"
const val ROUTE_LOWERADVANCED = "loweradvanced"
const val ROUTE_LOWERABS = "lowerabs"
const val ROUTE_UPPERABS = "upperabs"
const val ROUTE_BICEPSTRICEPS = "bicepstriceps"
const val ROUTE_FOREARMS = "forearms"
const val ROUTE_SHOULDERS = "shoulders"
const val ROUTE_KCHEST = "kchest"
const val ROUTE_LCHEST = "lchest"
const val ROUTE_LOWERLEGS = "lowerlegs"
const val ROUTE_UPPERLEGS = "upperlegs"

